server:
  port: 8080

# SpringDoc 配置
springdoc:
  #  api-docs:
  #    enabled: true
  #    path: "/api-docs"
  swagger-ui:
    enabled: true
    path: "/swagger-ui.html"
  # 配置扫描的包
  packagesToScan: com.sjuchat.sjucjava
  show-actuator: false
  cache:
    disabled: false
  pre-loading-enabled: true

# MySQL 配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sjuchat?useSSL=false&allowPublicKeyRetrieval=true
    username: lipeng
    password: 123456
